[alias]
rb = "run --bin main"
rrb = "run --release --bin main"
bbr = "build --release --bin main"
lint = "clippy --all -- -D warnings"
"lint:fix" = "clippy --all --fix --allow-staged -- -D warnings"
format = "fmt --all --check"
"format:fix" = "fmt --all"
